# Generated by Django 2.2.20 on 2021-05-02 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoredata', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScoreD',
            new_name='Scoredp',
        ),
        migrations.RenameModel(
            old_name='ScoreS',
            new_name='Scoresp',
        ),
    ]
