# Generated by Django 2.2.20 on 2021-05-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoredata', '0002_auto_20210502_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoresp',
            name='djlevel',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='scoresp',
            name='misscount',
            field=models.IntegerField(null=True),
        ),
    ]
