# Generated by Django 2.2.20 on 2021-05-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoredata', '0003_auto_20210504_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoredp',
            name='djlevel',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='scoredp',
            name='misscount',
            field=models.IntegerField(null=True),
        ),
    ]
