# Generated by Django 2.2.20 on 2021-05-08 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoredata', '0005_csvupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvupload',
            name='dj_id',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='csvupload',
            name='uploaded',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='アップロード画像'),
        ),
    ]
