# Generated by Django 2.2.20 on 2021-05-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoredata', '0006_auto_20210508_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvupload',
            name='uploaded',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name=''),
        ),
    ]
