# Generated by Django 2.2.20 on 2021-05-08 05:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoredata', '0007_auto_20210508_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvupload',
            name='uploaded',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['csv'])], verbose_name='※CSV形式のみ対応'),
        ),
    ]
