# Generated by Django 2.2.20 on 2021-05-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoredata', '0008_auto_20210508_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvupload',
            name='dj_id',
        ),
        migrations.AddField(
            model_name='csvupload',
            name='iidx_id',
            field=models.CharField(max_length=9, null=True, verbose_name='IIDX ID'),
        ),
    ]
