# Generated by Django 2.2.22 on 2021-05-09 07:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scoredata', '0009_auto_20210508_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ver_no', models.IntegerField()),
                ('ver_name', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
