# Generated by Django 2.2.22 on 2021-05-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoredata', '0010_versionlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versionlist',
            name='ver_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
